/* Program (code) related actions */
export const FETCH_PROGRAM_BEGIN = "FETCH_PROGRAM_BEGIN";
export const FETCH_PROGRAM_SUCCESS = "FETCH_PROGRAM_SUCCESS";
export const FETCH_PROGRAM_FAILURE = "FETCH_PROGRAM_FAILURE";

export const PUSH_PROGRAM_BEGIN = "PUSH_PROGRAM_BEGIN";
export const PUSH_PROGRAM_SUCCESS = "PUSH_PROGRAM_SUCCESS";
export const PUSH_PROGRAM_FAILURE = "PUSH_PROGRAM_FAILURE";

export const DELETE_PROGRAM_BEGIN = "DELETE_PROGRAM_BEGIN";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_FAILURE = "DELETE_PROGRAM_FAILURE";

export const SET_ACTIVE_PROGRAM = "SET_ACTIVE_PROGRAM";
export const CHECKOUT_REMOTE_CODE = "CHECKOUT_REMOTE_CODE";
export const EDIT_CHECKPOINT = "EDIT_CHECKPOINT";
export const PERFORM_EDIT = "PERFORM_EDIT";
export const FINISH_EDITING = "FINISH_EDITING";

/* Category related actions */
export const FETCH_CATEGORY_ARRAY_BEGIN = "FETCH_CATEGORY_ARRAY_BEGIN";
export const FETCH_CATEGORY_ARRAY_SUCCESS = "FETCH_CATEGORY_ARRAY_SUCCESS";
export const FETCH_CATEGORY_ARRAY_FAILURE = "FETCH_CATEGORY_ARRAY_FAILURE";

export const FETCH_CATEGORY_TREE_BEGIN = "FETCH_CATEGORY_TREE_BEGIN";
export const FETCH_CATEGORY_TREE_SUCCESS = "FETCH_CATEGORY_TREE_SUCCESS";
export const FETCH_CATEGORY_TREE_FAILURE = "FETCH_CATEGORY_TREE_FAILURE";

export const CREATE_CATEGORY_BEGIN = "CREATE_CATEGORY_BEGIN";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_BEGIN = "UPDATE_CATEGORY_BEGIN";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY_BEGIN = "DELETE_CATEGORY_BEGIN";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

/* Group related actions */
export const FETCH_GROUPS_BEGIN = "FETCH_GROUPS_BEGIN";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";

export const CREATE_GROUP_BEGIN = "CREATE_GROUP_BEGIN";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";
export const SET_GROUP_VIEW_MODE = "SET_GROUP_VIEW_MODE";